name: lvtn_app
description: "Ứng dụng di động Hệ thống quản lý tuyển sinh lớp 10 THPT"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_easy_recaptcha_v2: ^0.1.0
  dio: ^5.9.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  syncfusion_flutter_pdfviewer: ^31.2.3
  device_info_plus: ^12.2.0
  syncfusion_flutter_core: ^31.2.3
  open_filex: ^4.7.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_dotenv: ^6.0.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.10.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/recaptcha.html
    - assets/fonts/
    - assets/images/
    - assets/files/
    - assets/images/background-pano.jpg
    - assets/images/process-1.jpg
    - assets/images/process-2.jpg
    - assets/images/process-3.jpg
    - assets/images/process-4.jpg
    - assets/images/SGDDT.png
    - assets/.env.prod
    - assets/.env.dev

  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/segoeui.ttf
          weight: 400
        - asset: assets/fonts/segoeuii.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/segoeuib.ttf
          weight: 700
        - asset: assets/fonts/segoeuil.ttf
          weight: 300
        - asset: assets/fonts/segoeuiz.ttf
          weight: 700
          style: italic

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/SGDDT.png"
  min_sdk_android: 21
